export const countrysData = [
  {
    id: 1,
    name: "Albania",
    code: "AL",
    phone_code: "+355",
    nationality: "Albanian",
  },
  {
    id: 2,
    name: "Algeria",
    code: "DZ",
    phone_code: "+213",
    nationality: "Algerian",
  },
  {
    id: 3,
    name: "Andorra",
    code: "AD",
    phone_code: "+376",
    nationality: "Andorran",
  },
  {
    id: 4,
    name: "Angola",
    code: "AO",
    phone_code: "+244",
    nationality: "Angolan",
  },
  {
    id: 5,
    name: "Argentina",
    code: "AR",
    phone_code: "+54",
    nationality: "Argentine",
  },
  {
    id: 6,
    name: "Armenia",
    code: "AM",
    phone_code: "+374",
    nationality: "Armenian",
  },
  {
    id: 7,
    name: "Australia",
    code: "AU",
    phone_code: "+61",
    nationality: "Australian",
  },
  {
    id: 8,
    name: "Austria",
    code: "AT",
    phone_code: "+43",
    nationality: "Austrian",
  },
  {
    id: 9,
    name: "Azerbaijan",
    code: "AZ",
    phone_code: "+994",
    nationality: "Azerbaijani",
  },
  {
    id: 10,
    name: "Bahamas",
    code: "BS",
    phone_code: "+1-242",
    nationality: "Bahamian",
  },
  {
    id: 11,
    name: "Bahrain",
    code: "BH",
    phone_code: "+973",
    nationality: "Bahraini",
  },
  {
    id: 12,
    name: "Bangladesh",
    code: "BD",
    phone_code: "+880",
    nationality: "Bangladeshi",
  },
  {
    id: 13,
    name: "Barbados",
    code: "BB",
    phone_code: "+1-246",
    nationality: "Barbadian",
  },
  {
    id: 14,
    name: "Belarus",
    code: "BY",
    phone_code: "+375",
    nationality: "Belarusian",
  },
  {
    id: 15,
    name: "Belgium",
    code: "BE",
    phone_code: "+32",
    nationality: "Belgian",
  },
  {
    id: 16,
    name: "Belize",
    code: "BZ",
    phone_code: "+501",
    nationality: "Belizean",
  },
  {
    id: 17,
    name: "Benin",
    code: "BJ",
    phone_code: "+229",
    nationality: "Beninese",
  },
  {
    id: 18,
    name: "Bhutan",
    code: "BT",
    phone_code: "+975",
    nationality: "Bhutanese",
  },
  {
    id: 19,
    name: "Bolivia",
    code: "BO",
    phone_code: "+591",
    nationality: "Bolivian",
  },
  {
    id: 20,
    name: "Bosnia and Herzegovina",
    code: "BA",
    phone_code: "+387",
    nationality: "Bosnian",
  },
  {
    id: 21,
    name: "Botswana",
    code: "BW",
    phone_code: "+267",
    nationality: "Motswana",
  },
  {
    id: 22,
    name: "Brazil",
    code: "BR",
    phone_code: "+55",
    nationality: "Brazilian",
  },
  {
    id: 23,
    name: "Brunei",
    code: "BN",
    phone_code: "+673",
    nationality: "Bruneian",
  },
  {
    id: 24,
    name: "Bulgaria",
    code: "BG",
    phone_code: "+359",
    nationality: "Bulgarian",
  },
  {
    id: 25,
    name: "Burkina Faso",
    code: "BF",
    phone_code: "+226",
    nationality: "Burkinabe",
  },
  {
    id: 26,
    name: "Burundi",
    code: "BI",
    phone_code: "+257",
    nationality: "Burundian",
  },
  {
    id: 27,
    name: "Cambodia",
    code: "KH",
    phone_code: "+855",
    nationality: "Cambodian",
  },
  {
    id: 28,
    name: "Cameroon",
    code: "CM",
    phone_code: "+237",
    nationality: "Cameroonian",
  },
  {
    id: 29,
    name: "Canada",
    code: "CA",
    phone_code: "+1",
    nationality: "Canadian",
  },
  {
    id: 30,
    name: "Cape Verde",
    code: "CV",
    phone_code: "+238",
    nationality: "Cape Verdean",
  },
  {
    id: 31,
    name: "Central African Republic",
    code: "CF",
    phone_code: "+236",
    nationality: "Central African",
  },
  {
    id: 32,
    name: "Chad",
    code: "TD",
    phone_code: "+235",
    nationality: "Chadian",
  },
  {
    id: 33,
    name: "Chile",
    code: "CL",
    phone_code: "+56",
    nationality: "Chilean",
  },
  {
    id: 34,
    name: "China",
    code: "CN",
    phone_code: "+86",
    nationality: "Chinese",
  },
  {
    id: 35,
    name: "Colombia",
    code: "CO",
    phone_code: "+57",
    nationality: "Colombian",
  },
  {
    id: 36,
    name: "Comoros",
    code: "KM",
    phone_code: "+269",
    nationality: "Comoran",
  },
  {
    id: 37,
    name: "Costa Rica",
    code: "CR",
    phone_code: "+506",
    nationality: "Costa Rican",
  },
  {
    id: 38,
    name: "Croatia",
    code: "HR",
    phone_code: "+385",
    nationality: "Croatian",
  },
  {
    id: 39,
    name: "Cuba",
    code: "CU",
    phone_code: "+53",
    nationality: "Cuban",
  },
  {
    id: 40,
    name: "Cyprus",
    code: "CY",
    phone_code: "+357",
    nationality: "Cypriot",
  },
  {
    id: 41,
    name: "Czech Republic",
    code: "CZ",
    phone_code: "+420",
    nationality: "Czech",
  },
  {
    id: 42,
    name: "Denmark",
    code: "DK",
    phone_code: "+45",
    nationality: "Danish",
  },
  {
    id: 43,
    name: "Djibouti",
    code: "DJ",
    phone_code: "+253",
    nationality: "Djiboutian",
  },
  {
    id: 44,
    name: "Dominica",
    code: "DM",
    phone_code: "+1-767",
    nationality: "Dominican",
  },
  {
    id: 45,
    name: "Ecuador",
    code: "EC",
    phone_code: "+593",
    nationality: "Ecuadorian",
  },
  {
    id: 46,
    name: "Egypt",
    code: "EG",
    phone_code: "+20",
    nationality: "Egyptian",
  },
  {
    id: 47,
    name: "El Salvador",
    code: "SV",
    phone_code: "+503",
    nationality: "Salvadoran",
  },
  {
    id: 48,
    name: "Equatorial Guinea",
    code: "GQ",
    phone_code: "+240",
    nationality: "Equatorial Guinean",
  },
  {
    id: 49,
    name: "Eritrea",
    code: "ER",
    phone_code: "+291",
    nationality: "Eritrean",
  },
  {
    id: 50,
    name: "Estonia",
    code: "EE",
    phone_code: "+372",
    nationality: "Estonian",
  },
  {
    id: 51,
    name: "Ethiopia",
    code: "ET",
    phone_code: "+251",
    nationality: "Ethiopian",
  },
  {
    id: 52,
    name: "Fiji",
    code: "FJ",
    phone_code: "+679",
    nationality: "Fijian",
  },
  {
    id: 53,
    name: "Finland",
    code: "FI",
    phone_code: "+358",
    nationality: "Finnish",
  },
  {
    id: 54,
    name: "France",
    code: "FR",
    phone_code: "+33",
    nationality: "French",
  },
  {
    id: 55,
    name: "Gabon",
    code: "GA",
    phone_code: "+241",
    nationality: "Gabonese",
  },
  {
    id: 56,
    name: "Gambia",
    code: "GM",
    phone_code: "+220",
    nationality: "Gambian",
  },
  {
    id: 57,
    name: "Georgia",
    code: "GE",
    phone_code: "+995",
    nationality: "Georgian",
  },
  {
    id: 58,
    name: "Germany",
    code: "DE",
    phone_code: "+49",
    nationality: "German",
  },
  {
    id: 59,
    name: "Ghana",
    code: "GH",
    phone_code: "+233",
    nationality: "Ghanaian",
  },
  {
    id: 60,
    name: "Greece",
    code: "GR",
    phone_code: "+30",
    nationality: "Greek",
  },
  {
    id: 61,
    name: "Grenada",
    code: "GD",
    phone_code: "+1-473",
    nationality: "Grenadian",
  },
  {
    id: 62,
    name: "Guatemala",
    code: "GT",
    phone_code: "+502",
    nationality: "Guatemalan",
  },
  {
    id: 63,
    name: "Guinea",
    code: "GN",
    phone_code: "+224",
    nationality: "Guinean",
  },
  {
    id: 64,
    name: "Guinea-Bissau",
    code: "GW",
    phone_code: "+245",
    nationality: "Guineann",
  },
  {
    id: 65,
    name: "Guyana",
    code: "GY",
    phone_code: "+592",
    nationality: "Guyanese",
  },
  {
    id: 66,
    name: "Haiti",
    code: "HT",
    phone_code: "+509",
    nationality: "Haitian",
  },
  {
    id: 67,
    name: "Honduras",
    code: "HN",
    phone_code: "+504",
    nationality: "Honduran",
  },
  {
    id: 68,
    name: "Hungary",
    code: "HU",
    phone_code: "+36",
    nationality: "Hungarian",
  },
  {
    id: 69,
    name: "Iceland",
    code: "IS",
    phone_code: "+354",
    nationality: "Icelandic",
  },
  {
    id: 70,
    name: "India",
    code: "IN",
    phone_code: "+91",
    nationality: "Indian",
  },
  {
    id: 71,
    name: "Indonesia",
    code: "ID",
    phone_code: "+62",
    nationality: "Indonesian",
  },
  {
    id: 72,
    name: "Iran",
    code: "IR",
    phone_code: "+98",
    nationality: "Iranian",
  },
  {
    id: 73,
    name: "Iraq",
    code: "IQ",
    phone_code: "+964",
    nationality: "Iraqi",
  },
  {
    id: 74,
    name: "Ireland",
    code: "IE",
    phone_code: "+353",
    nationality: "Irish",
  },
  {
    id: 75,
    name: "Israel",
    code: "IL",
    phone_code: "+972",
    nationality: "Israeli",
  },
  {
    id: 76,
    name: "Italy",
    code: "IT",
    phone_code: "+39",
    nationality: "Italian",
  },
  {
    id: 77,
    name: "Ivory Coast",
    code: "CI",
    phone_code: "+225",
    nationality: "Ivorian",
  },
  {
    id: 78,
    name: "Jamaica",
    code: "JM",
    phone_code: "+1-876",
    nationality: "Jamaican",
  },
  {
    id: 79,
    name: "Japan",
    code: "JP",
    phone_code: "+81",
    nationality: "Japanese",
  },
  {
    id: 80,
    name: "Jordan",
    code: "JO",
    phone_code: "+962",
    nationality: "Jordanian",
  },
  {
    id: 81,
    name: "Kazakhstan",
    code: "KZ",
    phone_code: "+7",
    nationality: "Kazakh",
  },
  {
    id: 82,
    name: "Kenya",
    code: "KE",
    phone_code: "+254",
    nationality: "Kenyan",
  },
  {
    id: 83,
    name: "Kiribati",
    code: "KI",
    phone_code: "+686",
    nationality: "Kiribati",
  },
  {
    id: 84,
    name: "Kuwait",
    code: "KW",
    phone_code: "+965",
    nationality: "Kuwaiti",
  },
  {
    id: 85,
    name: "Kyrgyzstan",
    code: "KG",
    phone_code: "+996",
    nationality: "Kyrgyz",
  },
  {
    id: 86,
    name: "Laos",
    code: "LA",
    phone_code: "+856",
    nationality: "Lao",
  },
  {
    id: 87,
    name: "Latvia",
    code: "LV",
    phone_code: "+371",
    nationality: "Latvian",
  },
  {
    id: 88,
    name: "Lebanon",
    code: "LB",
    phone_code: "+961",
    nationality: "Lebanese",
  },
  {
    id: 89,
    name: "Lesotho",
    code: "LS",
    phone_code: "+266",
    nationality: "Basotho",
  },
  {
    id: 90,
    name: "Liberia",
    code: "LR",
    phone_code: "+231",
    nationality: "Liberian",
  },
  {
    id: 91,
    name: "Libya",
    code: "LY",
    phone_code: "+218",
    nationality: "Libyan",
  },
  {
    id: 92,
    name: "Liechtenstein",
    code: "LI",
    phone_code: "+423",
    nationality: "Liechtensteiner",
  },
  {
    id: 93,
    name: "Lithuania",
    code: "LT",
    phone_code: "+370",
    nationality: "Lithuanian",
  },
  {
    id: 94,
    name: "Luxembourg",
    code: "LU",
    phone_code: "+352",
    nationality: "Luxembourgish",
  },
  {
    id: 95,
    name: "Madagascar",
    code: "MG",
    phone_code: "+261",
    nationality: "Malagasy",
  },
  {
    id: 96,
    name: "Malawi",
    code: "MW",
    phone_code: "+265",
    nationality: "Malawian",
  },
  {
    id: 97,
    name: "Malaysia",
    code: "MY",
    phone_code: "+60",
    nationality: "Malaysian",
  },
  {
    id: 98,
    name: "Maldives",
    code: "MV",
    phone_code: "+960",
    nationality: "Maldivian",
  },
  {
    id: 99,
    name: "Mali",
    code: "ML",
    phone_code: "+223",
    nationality: "Malian",
  },
  {
    id: 100,
    name: "Malta",
    code: "MT",
    phone_code: "+356",
    nationality: "Maltese",
  },
  {
    id: 101,
    name: "Marshall Islands",
    code: "MH",
    phone_code: "+692",
    nationality: "Marshallese",
  },
  {
    id: 102,
    name: "Mauritania",
    code: "MR",
    phone_code: "+222",
    nationality: "Mauritanian",
  },
  {
    id: 103,
    name: "Mauritius",
    code: "MU",
    phone_code: "+230",
    nationality: "Mauritian",
  },
  {
    id: 104,
    name: "Mexico",
    code: "MX",
    phone_code: "+52",
    nationality: "Mexican",
  },
  {
    id: 105,
    name: "Micronesia",
    code: "FM",
    phone_code: "+691",
    nationality: "Micronesian",
  },
  {
    id: 106,
    name: "Moldova",
    code: "MD",
    phone_code: "+373",
    nationality: "Moldovan",
  },
  {
    id: 107,
    name: "Monaco",
    code: "MC",
    phone_code: "+377",
    nationality: "Monacan",
  },
  {
    id: 108,
    name: "Mongolia",
    code: "MN",
    phone_code: "+976",
    nationality: "Mongolian",
  },
  {
    id: 109,
    name: "Montenegro",
    code: "ME",
    phone_code: "+382",
    nationality: "Montenegrin",
  },
  {
    id: 110,
    name: "Morocco",
    code: "MA",
    phone_code: "+212",
    nationality: "Moroccan",
  },
  {
    id: 111,
    name: "Mozambique",
    code: "MZ",
    phone_code: "+258",
    nationality: "Mozambican",
  },
  {
    id: 112,
    name: "Myanmar",
    code: "MM",
    phone_code: "+95",
    nationality: "Burmese",
  },
  {
    id: 113,
    name: "Namibia",
    code: "NA",
    phone_code: "+264",
    nationality: "Namibian",
  },
  {
    id: 114,
    name: "Nauru",
    code: "NR",
    phone_code: "+674",
    nationality: "Nauruan",
  },
  {
    id: 115,
    name: "Nepal",
    code: "NP",
    phone_code: "+977",
    nationality: "Nepalese",
  },
  {
    id: 116,
    name: "Netherlands",
    code: "NL",
    phone_code: "+31",
    nationality: "Dutch",
  },
  {
    id: 117,
    name: "New Zealand",
    code: "NZ",
    phone_code: "+64",
    nationality: "New Zealander",
  },
  {
    id: 118,
    name: "Nicaragua",
    code: "NI",
    phone_code: "+505",
    nationality: "Nicaraguan",
  },
  {
    id: 119,
    name: "Niger",
    code: "NE",
    phone_code: "+227",
    nationality: "Nigerien",
  },
  {
    id: 120,
    name: "Nigeria",
    code: "NG",
    phone_code: "+234",
    nationality: "Nigerian",
  },
  {
    id: 121,
    name: "North Korea",
    code: "KP",
    phone_code: "+850",
    nationality: "North Korean",
  },
  {
    id: 122,
    name: "North Macedonia",
    code: "MK",
    phone_code: "+389",
    nationality: "Macedonian",
  },
  {
    id: 123,
    name: "Norway",
    code: "NO",
    phone_code: "+47",
    nationality: "Norwegian",
  },
  {
    id: 124,
    name: "Oman",
    code: "OM",
    phone_code: "+968",
    nationality: "Omani",
  },
  {
    id: 125,
    name: "Pakistan",
    code: "PK",
    phone_code: "+92",
    nationality: "Pakistani",
  },
  {
    id: 126,
    name: "Palau",
    code: "PW",
    phone_code: "+680",
    nationality: "Palauan",
  },
  {
    id: 127,
    name: "Palestine",
    code: "PS",
    phone_code: "+970",
    nationality: "Palestinian",
  },
  {
    id: 128,
    name: "Panama",
    code: "PA",
    phone_code: "+507",
    nationality: "Panamanian",
  },
  {
    id: 129,
    name: "Papua New Guinea",
    code: "PG",
    phone_code: "+675",
    nationality: "Papua New Guinean",
  },
  {
    id: 130,
    name: "Paraguay",
    code: "PY",
    phone_code: "+595",
    nationality: "Paraguayan",
  },
  {
    id: 131,
    name: "Peru",
    code: "PE",
    phone_code: "+51",
    nationality: "Peruvian",
  },
  {
    id: 132,
    name: "Philippines",
    code: "PH",
    phone_code: "+63",
    nationality: "Filipino",
  },
  {
    id: 133,
    name: "Poland",
    code: "PL",
    phone_code: "+48",
    nationality: "Polish",
  },
  {
    id: 134,
    name: "Portugal",
    code: "PT",
    phone_code: "+351",
    nationality: "Portuguese",
  },
  {
    id: 135,
    name: "Qatar",
    code: "QA",
    phone_code: "+974",
    nationality: "Qatari",
  },
  {
    id: 136,
    name: "Romania",
    code: "RO",
    phone_code: "+40",
    nationality: "Romanian",
  },
  {
    id: 137,
    name: "Russia",
    code: "RU",
    phone_code: "+7",
    nationality: "Russian",
  },
  {
    id: 138,
    name: "Rwanda",
    code: "RW",
    phone_code: "+250",
    nationality: "Rwandan",
  },
  {
    id: 139,
    name: "Saint Kitts and Nevis",
    code: "KN",
    phone_code: "+1-869",
    nationality: "Kittitian or Nevisian",
  },
  {
    id: 140,
    name: "Saint Lucia",
    code: "LC",
    phone_code: "+1-758",
    nationality: "Saint Lucian",
  },
  {
    id: 141,
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    phone_code: "+1-784",
    nationality: "Vincentian",
  },
  {
    id: 142,
    name: "Samoa",
    code: "WS",
    phone_code: "+685",
    nationality: "Samoan",
  },
  {
    id: 143,
    name: "San Marino",
    code: "SM",
    phone_code: "+378",
    nationality: "Sammarinese",
  },
  {
    id: 144,
    name: "Sao Tome and Principe",
    code: "ST",
    phone_code: "+239",
    nationality: "Sao Tomean",
  },
  {
    id: 145,
    name: "Saudi Arabia",
    code: "SA",
    phone_code: "+966",
    nationality: "Saudi Arabian",
  },
  {
    id: 146,
    name: "Senegal",
    code: "SN",
    phone_code: "+221",
    nationality: "Senegalese",
  },
  {
    id: 147,
    name: "Serbia",
    code: "RS",
    phone_code: "+381",
    nationality: "Serbian",
  },
  {
    id: 148,
    name: "Seychelles",
    code: "SC",
    phone_code: "+248",
    nationality: "Seychellois",
  },
  {
    id: 149,
    name: "Sierra Leone",
    code: "SL",
    phone_code: "+232",
    nationality: "Sierra Leonean",
  },
  {
    id: 150,
    name: "Singapore",
    code: "SG",
    phone_code: "+65",
    nationality: "Singaporean",
  },
  {
    id: 151,
    name: "Slovakia",
    code: "SK",
    phone_code: "+421",
    nationality: "Slovak",
  },
  {
    id: 152,
    name: "Slovenia",
    code: "SI",
    phone_code: "+386",
    nationality: "Slovenian",
  },
  {
    id: 153,
    name: "Solomon Islands",
    code: "SB",
    phone_code: "+677",
    nationality: "Solomon Islander",
  },
  {
    id: 154,
    name: "Somalia",
    code: "SO",
    phone_code: "+252",
    nationality: "Somali",
  },
  {
    id: 155,
    name: "South Africa",
    code: "ZA",
    phone_code: "+27",
    nationality: "South African",
  },
  {
    id: 156,
    name: "South Korea",
    code: "KR",
    phone_code: "+82",
    nationality: "South Korean",
  },
  {
    id: 157,
    name: "South Sudan",
    code: "SS",
    phone_code: "+211",
    nationality: "South Sudanese",
  },
  {
    id: 158,
    name: "Spain",
    code: "ES",
    phone_code: "+34",
    nationality: "Spanish",
  },
  {
    id: 159,
    name: "Sri Lanka",
    code: "LK",
    phone_code: "+94",
    nationality: "Sri Lankan",
  },
  {
    id: 160,
    name: "Sudan",
    code: "SD",
    phone_code: "+249",
    nationality: "Sudanese",
  },
  {
    id: 161,
    name: "Suriname",
    code: "SR",
    phone_code: "+597",
    nationality: "Surinamese",
  },
  {
    id: 162,
    name: "Sweden",
    code: "SE",
    phone_code: "+46",
    nationality: "Swedish",
  },
  {
    id: 163,
    name: "Switzerland",
    code: "CH",
    phone_code: "+41",
    nationality: "Swiss",
  },
  {
    id: 164,
    name: "Syria",
    code: "SY",
    phone_code: "+963",
    nationality: "Syrian",
  },
  {
    id: 165,
    name: "Taiwan",
    code: "TW",
    phone_code: "+886",
    nationality: "Taiwanese",
  },
  {
    id: 166,
    name: "Tajikistan",
    code: "TJ",
    phone_code: "+992",
    nationality: "Tajik",
  },
  {
    id: 167,
    name: "Tanzania",
    code: "TZ",
    phone_code: "+255",
    nationality: "Tanzanian",
  },
  {
    id: 168,
    name: "Thailand",
    code: "TH",
    phone_code: "+66",
    nationality: "Thai",
  },
  {
    id: 169,
    name: "Togo",
    code: "TG",
    phone_code: "+228",
    nationality: "Togolese",
  },
  {
    id: 170,
    name: "Tonga",
    code: "TO",
    phone_code: "+676",
    nationality: "Tongan",
  },
  {
    id: 171,
    name: "Trinidad and Tobago",
    code: "TT",
    phone_code: "+1-868",
    nationality: "Trinidadian or Tobagonian",
  },
  {
    id: 172,
    name: "Tunisia",
    code: "TN",
    phone_code: "+216",
    nationality: "Tunisian",
  },
  {
    id: 173,
    name: "Turkey",
    code: "TR",
    phone_code: "+90",
    nationality: "Turkish",
  },
  {
    id: 174,
    name: "Turkmenistan",
    code: "TM",
    phone_code: "+993",
    nationality: "Turkmen",
  },
  {
    id: 175,
    name: "Tuvalu",
    code: "TV",
    phone_code: "+688",
    nationality: "Tuvaluan",
  },
  {
    id: 176,
    name: "Uganda",
    code: "UG",
    phone_code: "+256",
    nationality: "Ugandan",
  },
  {
    id: 177,
    name: "Ukraine",
    code: "UA",
    phone_code: "+380",
    nationality: "Ukrainian",
  },
  {
    id: 178,
    name: "United Arab Emirates",
    code: "AE",
    phone_code: "+971",
    nationality: "Emirati",
  },
  {
    id: 179,
    name: "United Kingdom",
    code: "GB",
    phone_code: "+44",
    nationality: "British",
  },
  {
    id: 180,
    name: "United States",
    code: "US",
    phone_code: "+1",
    nationality: "American",
  },
  {
    id: 181,
    name: "Uruguay",
    code: "UY",
    phone_code: "+598",
    nationality: "Uruguayan",
  },
  {
    id: 182,
    name: "Uzbekistan",
    code: "UZ",
    phone_code: "+998",
    nationality: "Uzbek",
  },
  {
    id: 183,
    name: "Vanuatu",
    code: "VU",
    phone_code: "+678",
    nationality: "Vanuatuan",
  },
  {
    id: 184,
    name: "Vatican City",
    code: "VA",
    phone_code: "+379",
    nationality: "Vatican",
  },
  {
    id: 185,
    name: "Venezuela",
    code: "VE",
    phone_code: "+58",
    nationality: "Venezuelan",
  },
  {
    id: 186,
    name: "Vietnam",
    code: "VN",
    phone_code: "+84",
    nationality: "Vietnamese",
  },
  {
    id: 187,
    name: "Yemen",
    code: "YE",
    phone_code: "+967",
    nationality: "Yemeni",
  },
  {
    id: 188,
    name: "Zambia",
    code: "ZM",
    phone_code: "+260",
    nationality: "Zambian",
  },
  {
    id: 189,
    name: "Zimbabwe",
    code: "ZW",
    phone_code: "+263",
    nationality: "Zimbabwean",
  },
];
